name: CMake tests

on:
  workflow_dispatch:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ninja-build
        version: 1.0
    - name: Configure CMake
      run: |
        sh ${{github.workspace}}/scripts/fetch-catch2.sh
        cmake -S ${{github.workspace}}                           \
              -B ${{github.workspace}}/build                     \
              -G "$(${{github.workspace}}/scripts/generator.sh)" \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}             \
              -DPTR_CONTAINERS_BUILD_TESTS=YES

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -C ${{env.BUILD_TYPE}}
